### ISSUE TITLE
Create new Money Currency and change Values from Board.

### ISSUE THREAD

**Issue by mathias124** [Gutterne/CDIO_Final#12]
Please chance the values such as 👍 
Starting values from 20M to 30.000 Kr.
Pass start Value from 2M to 4000 kr.
and all housing values.

**Comment by Marble5** [comment]
Starting values from changed from 20M to 30.000 Kr. in SettingsController.java
 Pass start Value from 2M to 4000 kr. in Board.java
Housing values, (houseprices) not rents, been changed in board.java aswell.

**Comment by Marble5** [comment]
Starting values from changed from 20M to 30.000 Kr. in SettingsController.java
 Pass start Value from 2M to 4000 kr. in Board.java
Housing values, (houseprices) not rents, been changed in board.java aswell.
